version: "3.8"
services:
  langchain_app:
    build: .
    container_name: langchain_app
    ports:
      - "8000:8000" # もしWebサーバーを起動するならポートを公開
    volumes: # ホストのコードをマウントしたい場合に使用（開発時など）
      - ./app:/app/app
    # command:       # Dockerfile の CMD を上書きする場合はこちら
    #   - "python"
    #   - "my_alternative_main.py"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
